"""Add geometry metrics to inspections

Revision ID: 05533e9fdbb2
Revises: 1095edfd995f
Create Date: 2026-05-26 08:00:46.602618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05533e9fdbb2'
down_revision = '1095edfd995f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('area_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_column('area_percentage')
        batch_op.drop_column('density')
        batch_op.drop_column('max_width')
        batch_op.drop_column('total_length')

    # ### end Alembic commands ###
